name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_SERVER }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: "."
        target: "/var/www/demo.siscon.dev" #deploy 4

    - name: Build and run Docker Compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_SERVER }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd /var/www/demo.siscon.dev
          docker-compose down
          docker-compose up -d --build

    - name: Generate/renew Let's Encrypt certificate
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_SERVER }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd /var/www/demo.siscon.dev
          docker-compose run --rm --entrypoint "\
            certbot certonly --webroot \
            --register-unsafely-without-email --agree-tos \
            --webroot-path=/var/www/certbot \
            --domain www.demo.siscon.dev --domain demo.siscon.dev \
            --rsa-key-size 4096 --verbose --keep-until-expiring certbot
